### ISSUE TITLE
lots of compile errors

### ISSUE THREAD

**Issue by jwombat** [ulrikdamm/UnityNonNull#2]
Inserted into project with Package Manager.
Whenever I click on the gameobject in the Hierarchy view I get a double message of
`type is not a supported pptr value
`
If I leave the field empty it turns red, as it's supposed to, but when I put in a value it remains red.

**Comment by ulrikdamm** [comment]
Which Unity version are you using, and which .NET runtime (legacy 3.5 or the new 4.0)?

**Comment by jwombat** [comment]
It’s 2018.3.6f1, with .NET 4.x for both Scripting Runtime Version and Api Compatibility Level. I’m trying with a string.

**Comment by ulrikdamm** [comment]
Ah, that's the problem, since string isn't an object reference type. I've just pushed a new version that fixes the error, and it introduces a `[NonEmpty]` attribute for value types, like string, to check that the string isn't empty. Hope you'll check it out :)

**Comment by jwombat** [comment]
Yes! Thank for providing this package.
